# Generated by Django 4.1.10 on 2024-01-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=450, null=True)),
                ('descricao', models.CharField(max_length=1500)),
                ('imagem', models.ImageField(blank=True, default=' ', null=True, upload_to='uploads/portifolio/imagens')),
                ('tag', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('usuarioID', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
