# Generated by Django 4.1.10 on 2024-01-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='tag',
            new_name='tags',
        ),
    ]
